[package]
name = "rusty-leetcode"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[build-dependencies]
cc = "1.0"